version: "2"
services:
  madsdb:
    network_mode: bridge
    hostname: madsdb
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
  madscore:
    network_mode: bridge
    hostname: madscore
    environment:
      - MADS_DB=objectcube
      - MADS_USER=object
      - MADS_PASS=object
      - MADS_HOST=madsdb
      - MADS_PORT=5432
    build:
      context: .
      dockerfile: containers/Dockerfile_core
    ports:
      - "26026:26026"
    links:
      - madsdb

