version: "2"
services:
  ocdb:
    network_mode: bridge
    hostname: ob-db
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
  api:
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    links:
      - ocdb
