FROM ubuntu:20.04


RUN apt-get update && apt-get upgrade -y
RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

RUN apt-get install -y cmake \
    build-essential \
    libpqxx-dev \
    libpq-dev \
    python3 \
    python3-venv \
    python3-dev \
    cmake \
    autoconf \
    libtool \
    pkg-config \
    git

WORKDIR /tmp

RUN git clone --recurse-submodules -b v1.34.0 https://github.com/grpc/grpc /var/local/git/grpc
RUN mkdir -p /var/local/git/grpc/cmake/build
RUN  cd /var/local/git/grpc/cmake/build && cmake -DgRPC_INSTALL=ON \
    -DgRPC_BUILD_TESTS=OFF \
    -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
    ../..

RUN cd /var/local/git/grpc/cmake/build && make
RUN cd /var/local/git/grpc/cmake/build && make install
