#!/bin/bash
set -euo pipefail

# This script re-generates proto and grpc objects for the MADS
# core.
#
# usage: ./scripts/update-core-proto.sh
#
# Note: In this project, we check-in artifacts generated by protoc.
# If any changes are made to proto or grpc declaration, we must
# update the generated output for all grpc based projects.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PROTO_DIR="$SCRIPT_DIR/../src/proto"

cd $PROTO_DIR
"$HOME/.local/bin"/protoc -I . --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` MADS.proto
"$HOME/.local/bin"/protoc -I . --cpp_out=. MADS.proto



