#!/bin/bash
set -euo pipefail

# This script re-generates proto and grpc objects for the MADS
# API project.
#
# usage: ./scripts/update-api-proto.sh
#
# Note: In this project, we check-in artifacts generated by protoc.
# If any changes are made to proto or grpc declaration, we must
# update the generated output for all grpc based projects.

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

API_PROJECT_DIR="$SCRIPT_DIR/../src/api"

function update_python_proto {
  pushd "$API_PROJECT_DIR"
  .venv/bin/python -m grpc_tools.protoc -I../proto --python_out=api --grpc_python_out=api ../proto/OC.proto
  popd
}

function main {
  update_python_proto
}

main "$@"

